# Generated by Django 5.2.12 on 2026-05-25 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source_django_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('display_name', models.CharField(max_length=512, unique=True)),
                ('sort_name', models.CharField(blank=True, max_length=512)),
                ('aliases', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['sort_name', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('journal_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source_django_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=512, unique=True)),
                ('place', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source_django_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('group_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source_django_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=1024)),
                ('group_type', models.CharField(choices=[('multivolume', 'Multivolume'), ('series', 'Series'), ('set', 'Set'), ('supplement_group', 'Supplement group'), ('related_group', 'Related group')], default='multivolume', max_length=32)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title', 'group_id'],
            },
        ),
        migrations.CreateModel(
            name='JournalIssue',
            fields=[
                ('journal_issue_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source_django_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('issue_number', models.CharField(blank=True, max_length=64)),
                ('volume', models.CharField(blank=True, max_length=64)),
                ('date_text', models.CharField(blank=True, max_length=128)),
                ('publication_details', models.TextField(blank=True)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='sources.journal')),
            ],
            options={
                'ordering': ['journal__title', 'year', 'issue_number'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source_django_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('source_code', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='sources.section')),
            ],
            options={
                'ordering': ['sort_order', 'source_code'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source_django_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=512)),
                ('tag_type', models.CharField(choices=[('general', 'General'), ('thematic', 'Thematic'), ('geographic', 'Geographic'), ('issuer', 'Issuer'), ('name', 'Name')], default='general', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='sources.tag')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('work_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source_django_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('source_sequence', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('source_number', models.PositiveIntegerField(db_index=True)),
                ('source_page_marker', models.CharField(blank=True, max_length=32)),
                ('work_type', models.CharField(choices=[('book', 'Book'), ('article', 'Article'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('raw_author_string', models.TextField(blank=True)),
                ('title', models.TextField()),
                ('subtitle', models.TextField(blank=True)),
                ('volume_number', models.CharField(blank=True, max_length=64)),
                ('responsibility_note', models.TextField(blank=True)),
                ('host_title', models.TextField(blank=True)),
                ('publication_place', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('physical_description', models.TextField(blank=True)),
                ('article_pages', models.CharField(blank=True, max_length=128)),
                ('publication_details', models.TextField(blank=True)),
                ('public_review', models.TextField(blank=True)),
                ('inferred_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='sources.language')),
                ('source_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_works', to='sources.section')),
            ],
            options={
                'ordering': ['source_sequence', 'source_number'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source_django_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=1024)),
                ('publication_details', models.TextField(blank=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('source_text', models.TextField(blank=True)),
                ('parent_work', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_collection', to='sources.work')),
            ],
            options={
                'ordering': ['title', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source_django_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=255)),
                ('page_count', models.CharField(blank=True, max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=32)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='sources.work')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('source_django_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('pages', models.CharField(blank=True, max_length=128)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='sources.collection')),
                ('journal_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='sources.journalissue')),
                ('container_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contained_articles', to='sources.work')),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='sources.work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(blank=True, max_length=128)),
                ('source_text', models.CharField(blank=True, max_length=512)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.author')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.work')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='work',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='works', through='sources.WorkAuthor', to='sources.author'),
        ),
        migrations.CreateModel(
            name='WorkGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sources.workgroup')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='sources.work')),
            ],
            options={
                'ordering': ['sort_order', 'work__volume_number', 'work__inferred_year', 'work__title'],
            },
        ),
        migrations.CreateModel(
            name='WorkTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('source_text', models.CharField(blank=True, max_length=255)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sources.tag')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.work')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='work',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='works', through='sources.WorkTag', to='sources.tag'),
        ),
        migrations.AddConstraint(
            model_name='journalissue',
            constraint=models.UniqueConstraint(fields=('journal', 'year', 'issue_number', 'volume'), name='sources_journal_issue_unique_identity'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('parent', 'title'), name='sources_tag_unique_parent_title'),
        ),
        migrations.AddConstraint(
            model_name='workauthor',
            constraint=models.UniqueConstraint(fields=('work', 'author', 'role'), name='sources_work_author_unique_role'),
        ),
        migrations.AddConstraint(
            model_name='workgroupitem',
            constraint=models.UniqueConstraint(fields=('group', 'work'), name='sources_work_group_item_unique_group_work'),
        ),
        migrations.AddConstraint(
            model_name='worktag',
            constraint=models.UniqueConstraint(fields=('work', 'tag'), name='sources_work_tag_unique'),
        ),
    ]
