# Generated by Django 5.2.12 on 2026-05-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='location_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='page_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='page_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='pages_raw',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='article',
            name='placement_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='authority_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='author',
            name='heading_name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='author',
            name='person_dates',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='journal',
            name='end_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='issn',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='journal',
            name='numbering_end',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='journal',
            name='numbering_start',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='journal',
            name='parallel_title',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='journal',
            name='periodicity',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='journal',
            name='publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='journal',
            name='responsibility_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='start_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='title_history_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='title_remainder',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='chronology',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='enumeration',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='gross_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='isbn',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='issn',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='parallel_title',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='part_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='publication_date',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='publication_place',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='responsibility_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journalissue',
            name='title_remainder',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='work',
            name='access_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='accompanying_material',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='work',
            name='additional_edition_statement',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='work',
            name='bibliography_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='work',
            name='carrier_type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='work',
            name='content_type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='work',
            name='contents_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='work',
            name='copyright_date',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='work',
            name='description_status',
            field=models.CharField(choices=[('parsed', 'Parsed'), ('partial', 'Partial'), ('raw_only', 'Raw only'), ('needs_review', 'Needs review')], default='raw_only', max_length=32),
        ),
        migrations.AddField(
            model_name='work',
            name='dimensions',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='work',
            name='doi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='work',
            name='edition_statement',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='work',
            name='extent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='work',
            name='illustrations',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='work',
            name='index_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='work',
            name='isbn',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='work',
            name='issn',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='work',
            name='manufacture_date',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='work',
            name='manufacture_place',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='work',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='work',
            name='media_type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='work',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='work',
            name='parallel_title',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='work',
            name='part_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='work',
            name='part_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='work',
            name='publication_date',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='work',
            name='responsibility_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='work',
            name='series_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='work',
            name='title_remainder',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='work',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='workauthor',
            name='include_in_responsibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workauthor',
            name='is_primary_heading',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workauthor',
            name='name_as_printed',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
