# Generated by Django 5.2.12 on 2026-05-25 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_periodical_source_issue_articleplacement_sourcegroup_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='journalissue',
            name='sources_journal_issue_unique_identity',
        ),
    ]
