# Generated by Django 5.2.12 on 2026-05-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_remove_journalissue_sources_journal_issue_unique_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='circulation',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='work',
            name='circulation',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
