# Generated by Django 5.2.12 on 2026-05-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_add_circulation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='is_container',
            field=models.BooleanField(default=False),
        ),
    ]
