# Generated by Django 5.2.12 on 2026-05-26 06:41

from django.db import migrations, models


def mark_existing_containers(apps, schema_editor):
    Work = apps.get_model("sources", "Work")
    Article = apps.get_model("sources", "Article")
    container_ids = set(Article.objects.exclude(container_work_id=None).values_list("container_work_id", flat=True))
    flagged_ids = set(Work.objects.filter(is_container=True).values_list("work_id", flat=True))
    ids = container_ids | flagged_ids
    if ids:
        Work.objects.filter(work_id__in=ids).update(work_type="container", is_container=True)


def unmark_existing_containers(apps, schema_editor):
    Work = apps.get_model("sources", "Work")
    Work.objects.filter(work_type="container").update(work_type="book")


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_add_work_container_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.CharField(choices=[('book', 'Book'), ('container', 'Container'), ('article', 'Article'), ('unknown', 'Unknown')], default='unknown', max_length=16),
        ),
        migrations.RunPython(mark_existing_containers, unmark_existing_containers),
    ]
