# Generated by Django 5.2.12 on 2026-05-26 08:56

from django.db import migrations, models


def copy_article_pages_to_work(apps, schema_editor):
    Article = apps.get_model("sources", "Article")
    Work = apps.get_model("sources", "Work")
    for article in Article.objects.exclude(page_start=None).iterator():
        Work.objects.filter(work_id=article.work_id, page_start=None).update(page_start=article.page_start)
    for article in Article.objects.exclude(page_end=None).iterator():
        Work.objects.filter(work_id=article.work_id, page_end=None).update(page_end=article.page_end)


def clear_work_page_bounds(apps, schema_editor):
    Work = apps.get_model("sources", "Work")
    Work.objects.update(page_start=None, page_end=None)


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0007_work_type_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='page_end',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='page_start',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(copy_article_pages_to_work, clear_work_page_bounds),
    ]
